#!/bin/bash

# Copyright (C) 2009 Google Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

# This is an example script that configures you /etc/network/interfaces after
# installation.  By default its sets up the system to use dhcp. To use it just
# put it in your CUSTOMIZE_DIR and make it executable.

## !!! This hook asumes that your NIC inside the VM is named eth0.
## !!! In modern distros you must disable the Predictable Network Interface
## !!! Names standard:
## !!!    gnt-instance modify -H kernel_args='... net.ifnames=0'

if [ -z "$TARGET" -o ! -d "$TARGET" ]; then
  echo "Missing target directory"
  exit 1
fi

if [ ! -d "$TARGET/etc/network" ]; then
  echo "Missing target network directory"
  exit 1
fi

if [ -z "$NIC_COUNT" ]; then
  echo "Missing NIC COUNT"
  exit 1
fi

if [ "$NIC_COUNT" -gt 0 ]; then

# check weather to use dhcp or static method
if [ -n "${NIC_0_IP}" ]; then
  _nic_0_method="static"
  if [ -z "${NIC_0_NETWORK_SUBNET}" ] ; then
    echo "Missing NETWORK SUBNET from gnt-network"
    exit 1
  fi
  if [ -z "${NIC_0_NETWORK_GATEWAY}" ]; then
    echo "Missing NETWORK GATEWAY from gnt-network"
    exit 1
  fi
  _nic_0_cfg_block="    address ${NIC_0_IP}
    netmask ${NIC_0_NETWORK_SUBNET##*/}
    gateway ${NIC_0_NETWORK_GATEWAY}"
else
  _nic_0_method="dhcp"
  _nic_0_cfg_block=""
fi

  cat > $TARGET/etc/network/interfaces <<EOF
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

auto lo
iface lo inet loopback

auto eth0
iface eth0 inet ${_nic_0_method}
${_nic_0_cfg_block}

EOF

fi
