#!/bin/sh
#
# This is an example script that sets the timezone to a given default,
# or to the one of the host is none is configured.

if [ -r confdata/timezone ]; then
  cp confdata/timezone $TARGET/etc/
else
  cp /etc/timezone $TARGET/etc/
fi

chroot $TARGET dpkg-reconfigure --frontend noninteractive tzdata
